### ISSUE TITLE
Add points for support answers

### ISSUE THREAD

**Issue by adiroiban** [chevah/gamification#2]
Maybe have an IRC notification when someone from the team is sending an email to CC support ... 

then we can use the current IRC log parser to rate it

**Comment by hcs0** [comment]
Ideally I'd like to be able to use some sort of helpdesk/ticketing software for support down the track.

**Comment by adiroiban** [comment]
Yes.... so having helpdesk/ticketing would be ideal

**Comment by adiroiban** [comment]
For now it will be implemented using the irc logs... we can create a new ticket once we have a dedicated support system

this was fixed in release 0.2.0 and is already available
